(function(){
const C={website:{letter:'A',title:'Main Website',description:'Pages, photos, menus, links, loading, and display problems.',articles:['photos','page','mobile']},business:{letter:'B',title:'Business HQ',description:'Partner access, sign-in, dashboard, forms, and account help.',articles:['hq-access','hq-controls','hq-profile']},email:{letter:'C',title:'Newsletter & Email',description:'Signup, welcome messages, browser views, and subscriptions.',articles:['missing-email','browser-email','unsubscribe']},privacy:{letter:'D',title:'Privacy & Xilo',description:'Privacy choices, saved chats, cookies, and data requests.',articles:['privacy-choices','xilo-chat','data-request']},contact:{letter:'E',title:'Contact & Inquiries',description:'Collaborations, bookings, business messages, and replies.',articles:['business-inquiry','missing-reply']},accessibility:{letter:'F',title:'Accessibility',description:'Keyboard navigation, readability, mobile access, and assistance.',articles:['access-help','access-report']}};
const A={
photos:{c:'website',t:'Photos are not appearing',s:'Steps to take when the Photos page is blank or images do not load.',b:['Refresh the Photos page once. A temporary connection problem can leave the grid empty.','Try another browser or switch between Wi-Fi and cellular data.','If it remains empty, send a ticket with the page link, device, browser, and approximate time.']},
page:{c:'website',t:'A page or button is not working',s:'Report a broken link, control, menu, or page.',b:['Reload the page and try the action once more. Note the exact control you selected.','Send a ticket with the page address, expected result, actual result, device, and browser.']},
mobile:{c:'website',t:'The site looks wrong on mobile',s:'Help with overlapping, cropped, or unusually sized content.',b:['Reload after returning the device to portrait mode and check that browser zoom is near its default.','If the layout remains broken, send a ticket with the device, browser, and page.']},
'hq-access':{c:'business',t:'I cannot access Business HQ',s:'Sign-in and partner-access help for the Business HQ portal.',b:['Open Business HQ from the official Contact page and use the email connected to your partner access.','If access is missing, send a Business HQ ticket with your partner email and company. Never send a password or login code.']},
'hq-controls':{c:'business',t:'A Business HQ control is not working',s:'Report a dashboard action that fails, freezes, or does not save.',b:['Reload Business HQ and try the action once. Avoid submitting the same form repeatedly.','Send a ticket with the exact page, control, result, and approximate time.']},
'hq-profile':{c:'business',t:'My Business HQ information is incorrect',s:'Request a correction to partner or company details.',b:['Send a Business HQ ticket from the email connected to your access and describe the correction.','Do not include passwords, payment details, or identity documents.']},
'missing-email':{c:'email',t:'An email is not arriving',s:'Find a welcome email or newsletter that is missing.',b:['Check Spam, Junk, and Promotions, then search for “YourFavAlien.” Delivery can take a few minutes.','If it is still missing, send a ticket with the subscribed address and approximate signup time.']},
'browser-email':{c:'email',t:'View an email in the browser',s:'Use the web copy when an email client does not display a message correctly.',b:['Open the message and select “View this email in browser.” It should open that specific email.','If it opens the main website or an error page, send an Email ticket with the message and arrival date.']},
unsubscribe:{c:'email',t:'Unsubscribe from the newsletter',s:'Stop future newsletter messages.',b:['Use the unsubscribe link in the footer of the latest newsletter.','If it fails, send a Newsletter / email ticket using the subscribed address.']},
'privacy-choices':{c:'privacy',t:'Change privacy choices',s:'Review or change optional website storage.',b:['Open the main-site menu and choose Privacy Choices in the footer.','Choose your preference and save it. Essential site functions remain available.']},
'xilo-chat':{c:'privacy',t:'Clear a saved Xilo conversation',s:'Remove the conversation saved on your device.',b:['Open Xilo and clear the current conversation from its controls.','If it remains after reloading, send a Privacy / Xilo ticket.']},
'data-request':{c:'privacy',t:'Send a privacy or data request',s:'Ask about information connected to the site.',b:['Select Privacy / Xilo / data in the support form and explain the request.','Do not send sensitive identifiers. The crew will explain any verification needed.']},
'business-inquiry':{c:'contact',t:'Send a business inquiry',s:'The right route for collaborations, casting, press, and partnerships.',b:['Use the official Contact page and choose Business HQ. Include your company, request, and reply address.','Use support tickets when the website or an existing submission is not working.']},
'missing-reply':{c:'contact',t:'I did not receive a reply',s:'What to check after sending a general or business message.',b:['Check the reply address, Spam, and Junk. Response time varies by inquiry.','If the form may have failed, send a ticket with the date, form type, and subject.']},
'access-help':{c:'accessibility',t:'Get help using the website',s:'Help with keyboard, screen reader, zoom, or mobile access.',b:['Try refreshing after changing browser zoom or text size.','If you cannot reach or understand a section, send an Accessibility ticket with the page and assistive technology.']},
'access-report':{c:'accessibility',t:'Report an accessibility issue',s:'Tell the crew about a barrier so it can be investigated.',b:['Describe the task, page, and what stopped you. Include the device, browser, and assistive technology.','Never include passwords or private account codes.']}
};window.YFA_HELP={categories:C,articles:A};const au=id=>'/help-article.html?article='+encodeURIComponent(id),cu=id=>'/help-category.html?topic='+encodeURIComponent(id);
document.querySelectorAll('[data-help-search]').forEach(i=>{const r=i.parentElement.querySelector('.results');i.addEventListener('input',()=>{const q=i.value.trim().toLowerCase(),m=Object.entries(A).filter(([,a])=>(a.t+' '+a.s+' '+C[a.c].title).toLowerCase().includes(q)).slice(0,6);r.innerHTML=q?(m.length?m.map(([id,a])=>'<a class="result" href="'+au(id)+'"><b>'+a.t+'</b><small>'+C[a.c].title+'</small></a>').join(''):'<span class="result"><b>No articles found</b><small>Try another term or send a ticket.</small></span>'):'';r.classList.toggle('open',!!q)});i.addEventListener('keydown',e=>{if(e.key==='Enter'){const q=i.value.toLowerCase(),x=Object.entries(A).find(([,a])=>(a.t+' '+a.s).toLowerCase().includes(q));if(x)location.href=au(x[0])}})});
const p=new URLSearchParams(location.search),topic=p.get('topic'),aid=p.get('article');if(document.body.dataset.page==='category'){const c=C[topic]||C.website;document.title=c.title+' | YourFavAlien Support';document.querySelector('[data-letter]').textContent=c.letter;document.querySelector('[data-title]').textContent=c.title;document.querySelector('[data-description]').textContent=c.description;document.querySelector('[data-list]').innerHTML=c.articles.map((id,n)=>'<a class="article-link" href="'+au(id)+'"><small>ARTICLE '+String(n+1).padStart(2,'0')+'</small><div><h2>'+A[id].t+'</h2><p>'+A[id].s+'</p></div><span>→</span></a>').join('')}
if(document.body.dataset.page==='article'){const a=A[aid]||A.page,c=C[a.c];document.title=a.t+' | YourFavAlien Support';const bc=document.querySelector('[data-cat]');bc.textContent=c.title;bc.href=cu(a.c);document.querySelector('[data-title]').textContent=a.t;document.querySelector('[data-intro]').textContent=a.s;document.querySelector('[data-body]').innerHTML='<h2>What to do</h2><ol>'+a.b.map(x=>'<li>'+x+'</li>').join('')+'</ol><div class="note"><b>Still need help?</b><p>Return to the Help Center and send a support ticket.</p></div>';document.querySelector('[data-related]').innerHTML=c.articles.filter(id=>id!==aid).map(id=>'<a href="'+au(id)+'">'+A[id].t+'</a>').join('')}
const f=document.querySelector('#ticket');if(f){const id='YFA-'+new Date().toISOString().slice(2,10).replaceAll('-','')+'-'+Math.random().toString(36).slice(2,6).toUpperCase();f.querySelector('[name=ticket_id]').value=id;f.addEventListener('submit',()=>f.querySelector('[name=_subject]').value='YourFavAlien support ticket '+id+' — '+f.querySelector('[name=subject]').value)}
})();

(async function(){
if(document.body.classList.contains('support-admin-page'))return;
const u='https://yourfavalien-mothership.aydenmtz54.workers.dev/assets/support/support-center.json?v='+Date.now();let s;try{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('settings unavailable');s=await r.json();try{localStorage.setItem('yfa-support-settings',JSON.stringify(s))}catch(e){}}catch(e){try{s=JSON.parse(localStorage.getItem('yfa-support-settings')||'null')}catch(x){}if(!s)return}window.YFA_SUPPORT_SETTINGS=s;const d=document,c=s.colors||{},b=s.branding||{},co=s.contact||{};if(b.siteName)b.siteName=String(b.siteName).replaceAll('Your Favorite Alien','Your Fav Alien').replaceAll('YourFavAlien','Your Fav Alien');if(b.copyright)b.copyright=String(b.copyright).replaceAll('Your Favorite Alien','Your Fav Alien').replaceAll('YourFavAlien','Your Fav Alien');for(const[k,v]of Object.entries(c))if(v)d.documentElement.style.setProperty('--'+k,v);d.querySelectorAll('.brand').forEach(e=>{const icon=e.querySelector('.support-logo,.mark');e.textContent=(b.siteName&&b.siteName!=='Support Center'?b.siteName:'Your Fav Alien Support Center').replaceAll('Your Favorite Alien','Your Fav Alien').replaceAll('YourFavAlien','Your Fav Alien');if(icon)e.prepend(icon)});d.querySelectorAll('.footer-bottom>span:first-child').forEach(e=>e.textContent=(b.copyright&&b.copyright!=='© 2026 YourFavAlien Support Center. All rights reserved.'?b.copyright:'© 2026 Your Fav Alien Support Center. All rights reserved.'));d.querySelectorAll('a[href^="mailto:help@yourfavalien.com"]').forEach(e=>{e.href='mailto:'+(co.email||'help@yourfavalien.com');if(e.textContent.includes('@'))e.textContent=co.email||'help@yourfavalien.com'});
const ca=Array.isArray(s.categories)&&s.categories.length?s.categories:null,ar=Array.isArray(s.articles)&&s.articles.length?s.articles:null;if(ca&&ar){const C={},A={};ca.forEach(x=>C[x.id]={letter:x.letter,title:x.title,description:x.description,articles:x.articles||ar.filter(a=>a.category===x.id).map(a=>a.id)});ar.forEach(x=>A[x.id]={c:x.category,t:x.title,s:x.summary,b:Array.isArray(x.body)?x.body:String(x.body||'').split(/\r?\n/).filter(Boolean)});window.YFA_HELP={categories:C,articles:A};const grid=d.querySelector('.categories');if(grid)grid.innerHTML=Object.entries(C).map(([id,x])=>`<a class="category" href="/help-category.html?topic=${encodeURIComponent(id)}"><span class="category-top">${x.letter} <em>${x.articles.length} ARTICLES</em></span><span class="letter">${x.letter}</span><h3>${x.title}</h3><p>${x.description}</p><span class="arrow">VIEW TOPIC →</span></a>`).join('');const p=new URLSearchParams(location.search),t=p.get('topic'),id=p.get('article');if(d.body.dataset.page==='category'&&C[t]){const x=C[t];d.querySelector('[data-letter]').textContent=x.letter;d.querySelector('[data-title]').textContent=x.title;d.querySelector('[data-description]').textContent=x.description;d.querySelector('[data-list]').innerHTML=x.articles.filter(i=>A[i]).map((i,n)=>`<a class="article-link" href="/help-article.html?article=${encodeURIComponent(i)}"><small>ARTICLE ${String(n+1).padStart(2,'0')}</small><div><h2>${A[i].t}</h2><p>${A[i].s}</p></div><span>→</span></a>`).join('')}if(d.body.dataset.page==='article'&&A[id]){const a=A[id],x=C[a.c],bc=d.querySelector('[data-cat]');bc.textContent=x.title;bc.href='/help-category.html?topic='+encodeURIComponent(a.c);d.querySelector('[data-title]').textContent=a.t;d.querySelector('[data-intro]').textContent=a.s;d.querySelector('[data-body]').innerHTML='<h2>What to do</h2><ol>'+a.b.map(v=>'<li>'+v+'</li>').join('')+'</ol><div class="note"><b>Still need help?</b><p>Return to the Help Center and send a support ticket.</p></div>';d.querySelector('[data-related]').innerHTML=x.articles.filter(i=>i!==id&&A[i]).map(i=>`<a href="/help-article.html?article=${encodeURIComponent(i)}">${A[i].t}</a>`).join('')}}
const h=d.querySelector('.hero');if(h){if(b.heroLabel)h.querySelector('.label').textContent=b.heroLabel;if(b.heroTitle)h.querySelector('h1').textContent=b.heroTitle;if(b.heroCopy)h.querySelector('.hero-copy').textContent=b.heroCopy}const sh=d.querySelector('#topics .section-head');if(sh){const ps=sh.querySelectorAll('p');if(b.topicsLabel)ps[0].textContent=b.topicsLabel;if(b.topicsTitle)sh.querySelector('h2').textContent=b.topicsTitle;if(b.topicsCopy)ps[1].textContent=b.topicsCopy}const ticket=d.querySelector('#ticket');if(ticket&&co.ticketEnabled===false)ticket.closest('.contact').hidden=true;const ch=d.querySelector('.contact-hero');if(ch){if(co.title)ch.querySelector('h1').textContent=co.title;if(co.copy)ch.querySelector(':scope>p:last-child').textContent=co.copy}d.querySelectorAll('.contact-option').forEach(x=>{if(x.textContent.includes('Email Support')&&co.emailEnabled===false)x.hidden=true});const sys=d.querySelector('.systems');if(sys&&Array.isArray(s.statusServices)){sys.innerHTML=s.statusServices.map(x=>`<div class="system"><div><b>${x.name}</b><small>${x.description}</small></div><span class="state" ${x.url?(x.url.startsWith('http')?'data-external':'data-check')+'="'+x.url+'"':''}>${x.url?'Checking…':'Operational'}</span></div>`).join('');window.dispatchEvent(new Event('yfa-status-ready'))}
})();

(function(){
const header=document.querySelector('.header'),nav=header&&header.querySelector('.nav');if(!header||!nav||header.querySelector('.support-menu-toggle'))return;
nav.id=nav.id||'support-navigation';const button=document.createElement('button'),brandLogo=header.querySelector('.brand .support-logo');button.type='button';button.className='support-menu-toggle';button.setAttribute('aria-controls',nav.id);button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Open support menu');button.innerHTML='<img class="support-logo" src="'+(brandLogo?brandLogo.src:'/assets/favicon.png')+'" alt="">';header.querySelector('.header-in').insertBefore(button,nav);
const close=()=>{nav.classList.remove('is-open');button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Open support menu')};button.addEventListener('click',()=>{const open=nav.classList.toggle('is-open');button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Close support menu':'Open support menu')});nav.addEventListener('click',e=>{if(e.target.closest('a'))close()});document.addEventListener('click',e=>{if(!header.contains(e.target))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
})();
(async function(){
function cached(){try{return JSON.parse(localStorage.getItem('yfa-support-settings')||'null')}catch(e){return null}}
function swap(selector,url){if(!url)return;document.querySelectorAll(selector).forEach(brand=>{const current=brand.querySelector('.support-logo'),probe=new Image();probe.className='support-logo';probe.alt='';probe.onload=()=>{brand.querySelectorAll('.support-logo').forEach(image=>{if(image!==current)image.remove()});const mark=brand.querySelector('.mark');if(mark)mark.remove();if(current)current.src=url;else{probe.src=url;brand.prepend(probe)}};probe.src=url})}
function apply(settings){const m=settings&&settings.media;if(!m)return;swap('.header .brand,.support-menu-toggle',m.headerLogo||m['header-logo']||'');swap('.footer .brand',m.footerLogo||m['footer-logo']||'');const hero=document.querySelector('.hero'),background=m.heroBackground||m['hero-background']||'';if(hero&&background){hero.classList.add('has-support-background');hero.style.backgroundImage='url("'+String(background).replace(/["\\]/g,'')+'")'}}
let settings=window.YFA_SUPPORT_SETTINGS||cached();apply(settings);try{const response=await fetch('https://yourfavalien-mothership.aydenmtz54.workers.dev/assets/support/support-center.json?v='+Date.now(),{cache:'no-store'});if(response.ok){settings=await response.json();try{localStorage.setItem('yfa-support-settings',JSON.stringify(settings))}catch(e){}apply(settings)}}catch(e){apply(cached())}
})();
