(function(){'use strict';
const endpoint='https://yourfavalien-mothership.aydenmtz54.workers.dev/api/status',list=document.querySelector('.systems'),overall=document.getElementById('overall'),checked=document.getElementById('checked'),button=document.getElementById('refreshStatus');
const labels={operational:'Operational',maintenance:'Maintenance',degraded:'Service Issue',outage:'Unavailable'},escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
// Server replies alone cannot catch a page whose browser code has frozen. These
// hidden checks wait for the shared site shell to finish starting on real pages.
function checkRenderedPage(path){return new Promise(resolve=>{const frame=document.createElement('iframe'),started=performance.now();let complete=false;const finish=healthy=>{if(complete)return;complete=true;clearInterval(poll);clearTimeout(timeout);frame.remove();resolve({healthy,responseMs:Math.round(performance.now()-started)});};frame.hidden=true;frame.tabIndex=-1;frame.setAttribute('aria-hidden','true');frame.src=path+(path.includes('?')?'&':'?')+'status-check='+Date.now();const poll=setInterval(()=>{try{if(frame.contentWindow&&frame.contentWindow.__YFA_PAGE_READY__)finish(true);}catch(_){finish(false);}},100),timeout=setTimeout(()=>finish(false),9000);frame.addEventListener('error',()=>finish(false),{once:true});document.body.append(frame);});}
async function checkMainWebsite(){const checks=await Promise.all([checkRenderedPage('/about'),checkRenderedPage('/contact')]);return{healthy:checks.every(check=>check.healthy),responseMs:Math.max(...checks.map(check=>check.responseMs))};}
async function refresh(){button.disabled=true;button.textContent='CHECKING…';overall.className='overall checking';overall.innerHTML='<span class="dot"></span>Checking all systems…';list.querySelectorAll('.state').forEach(state=>{state.className='state checking';state.textContent='Checking…'});try{const [response,renderedMain]=await Promise.all([fetch(endpoint+'?v='+Date.now(),{cache:'no-store'}),checkMainWebsite()]);if(!response.ok)throw new Error('Status service unavailable');const data=await response.json(),services=Array.isArray(data.services)?data.services.slice():[],mainState=renderedMain.healthy?'operational':'outage',mainService={name:'Main Website',description:renderedMain.healthy?'Live page startup and navigation check':'The live page did not finish loading correctly',state:mainState,responseMs:renderedMain.responseMs},mainIndex=services.findIndex(service=>/main website/i.test(service.name||''));if(mainIndex>=0)services[mainIndex]=mainService;else services.unshift(mainService);const actualOverall=renderedMain.healthy?(data.overall||'outage'):(data.overall==='maintenance'?'maintenance':'outage');list.innerHTML=services.map(service=>'<div class="system"><div><b>'+escape(service.name)+'</b><small>'+escape(service.description)+'</small></div><span class="state '+escape(service.state)+'">'+escape(labels[service.state]||'Unknown')+(Number.isFinite(service.responseMs)?'<small>'+service.responseMs+' ms</small>':'')+'</span></div>').join('');const overallText={operational:'All systems operational',maintenance:'Scheduled maintenance in progress',degraded:'Some systems are experiencing issues',outage:'A service is currently unavailable'}[actualOverall]||'Status unavailable';overall.className='overall '+actualOverall;overall.innerHTML='<span class="dot"></span>'+overallText+(data.maintenance&&data.maintenanceMessage?'<small>'+escape(data.maintenanceMessage)+'</small>':'');checked.textContent='Last checked '+new Date().toLocaleString()+' · includes a real page-startup check.'}catch(error){overall.className='overall outage';overall.innerHTML='<span class="dot"></span>Status check unavailable';checked.textContent='We could not refresh the status. Please try again.'}finally{button.disabled=false;button.textContent='REFRESH STATUS'}}
button.addEventListener('click',refresh);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh()});window.addEventListener('yfa-status-ready',refresh,{once:true});refresh();setInterval(refresh,60000);
})();
